- features.html
Presentation of the "saved searches" feature on the features page.
> add saved seaches feature

- features.html
> Move or copy emails from one account to another

- license.html
https://github.com/jasonmunro/cypht/issues/333
> Previously changed from GPL to LGPL

- contribute.html
- features.html
- index.html
- license.html
- modules.html
- security.html
- tests.html
added button to open the chat.
> [NEW] ADD GITTER SIDECAR TO OUR PUBLIC WEBSITE

- install.html
> correct permalink to composer.json

- bootstrap.bundle.min.js
- contribute.html
- documentation.html
- features.html
- index.html
- install.html
- jquery.slim.min.js
- license.html
- modules.html
- security.html
- tests.html
Menu links were not the same for all pages. Also, the menu toggle on mobile devices was not working as expected.
Related to https://github.com/jasonmunro/cypht-website/issues/33
> Navigation menu content not consistent

- README.md
This will help to test if cron job is running as well set to be running all 5minutes everyday.
Related task: [https://avan.tech/item98879](https://avan.tech/item98879)
@marclaporte , @josaphatim.
> [DOC]: some more information about cypht

- contribute.html
- documentation.html
- features.html
- index.html
- install.html
- license.html
- modules.html
- security.html
- site.css
- tests.html
This documantation as been set to help any one that would like to make any update on the website without strugle on the process to follow.
Task : https://avan.tech/item82621-Add-a-link-in-the-footer-of-Cypht-org-about-how-to-update-site-Cypht-org
issue : closes #34
> provide more detail on website contribution

- contribute.html
Enhance clarity, correct grammatical errors ...
> Review contribute.html file 

- install-2x.html
[Related Comment Thread](https://avan.tech/item45468-Team-Butembo-Test-Cypht-org-as-a-new-user#threadId74359)
> [DOC]install-2x.html: Updating documentation for Cypht version2

- index.html
- install-2x.html
- install.html
- site.css
[Related comment issue](https://github.com/cypht-org/cypht-website/pull/49#issuecomment-2130672851)
> [DOC]install.html, install-1x.html, install-2x.html: reworking installation files

- index.html
- install-1x.html
- install-2x.html
- install.html
- security.html
Jason is unavailable these days. He is the founder, but no longer active and no longer the main contact.
So removing his email. It's better that people come to the chat room.
> [DOC]Cypht: From a jason project to a community project

- install-1x.html
- install-2x.html
- install.html
This PR fix some small typos found on the docker instructions section
> [DOC] Update installation instructions for docker-compose files (fix small typos)

- install-1x.html
- install-2x.html
- install.html
Cypht v2.1.0 has been released here: https://github.com/cypht-org/cypht/releases/tag/v2.1.0. Cypht.org needs an update.
> [UPD]install.html, install-1x.html, install-2x.html: An update for Cypht2.1

- contribute.html
- features.html
- index.html
- license.html
- modules.html
- security.html
- tests.html
https://github.com/cypht-org/cypht-website/issues/39
> remove sidecar script from all HTML pages

- email-filters.html
- features.html
[DOC]Email filters: Cypht documentation about sieve filters
> [DOC]Email filters: Cypht documentation about sieve filters

- documentation.html
> [DOC]Some other fixes

- install-1x.html
- install-2x.html
- install.html
In this PR i updated doc changing 2.1.x to 2.2.x
> Update Cypht Doc version

- install-1x.html
- install-2x.html
- install.html
Sent the different fixes in different commits in case you want to cherry pick, but feel free to squash if all of them look good!
> Some additions & typo fixes for install docs

- features.html
- modules.html
[https://github.com/cypht-org/cypht/issues/13#issuecomment-2425586088](https://github.com/cypht-org/cypht/issues/13#issuecomment-2425586088)
> Correct Tag module description

- install-2x.html
- install.html
Everything is said in the commit title! Which I used as pull request title. Sorry.
EDIT: The chapter copying is done because as of now, https://www.cypht.org/install.html shows config instructions based on no-longer existing INI links/files
> Copied chapter 8 from 2.x to master, changed 2.x hrefs to use 2.x branch

- contribute.html
- developers-documentation.html
- documentation.html
- email-filters.html
- features.html
- how-to-join.html
- index.html
- install-1x.html
- install-2x.html
- install.html
- license.html
- modules.html
- security.html
Parent PR: [#83](https://github.com/cypht-org/cypht-website/pull/83)
> [DOC]Renaming Menu FOR-DEVELOPERS=>DEVS-DOC

- developers-documentation.html
As of [#82](https://github.com/cypht-org/cypht-website/pull/82/)
> [DOC]:developers-documentation.html: Adding Edit page on Github link

- developers-documentation.html
> [DOC] Add related links to the developers documentation

- cecil.yml
- layouts/page.html.twig
- layouts/partials/install.html.twig
- pages/install-1x.md
- pages/install-2x.md
Reverts cypht-org/cypht-website#98
@Denperidge Your changes were pointing to `dev` branch instead of master. Please fix. Thanks.
> Revert "Install: merged pages & added redirects"

- layouts/page.html.twig
[Related issue](https://github.com/cypht-org/cypht-website/issues/111)
> [FIX]layouts/page.html.twig: Fix edit page broken link

- pages/install.md
[Related comment](https://github.com/cypht-org/cypht-website/issues/113#issuecomment-2762787866)
> [DOC]install.md:correcting php versions for Cypht versions

- layouts/page.html.twig
Badabing badaboom, closes #111! Sorry for not getting on this sooner
> [FIX] "Page on GitHub" link

- pages/install.md
Related [issue](https://github.com/cypht-org/cypht/issues/1154)
> [ENH] install.md: Add Cpanel script install

- pages/install.md
Related issue: [https://github.com/cypht-org/cypht/issues/1552](https://github.com/cypht-org/cypht/issues/1552)
> [UPD] Docker: Improve Cypht Docker Installation documentation
